nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: "The B2B mobile showcase: simple, fast, and exclusive !"
            version: 2.0.0
        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Obtain the JWT token for logging in
                    requestBody:
                        description: Create a new JWT token
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Retrieve the JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '400':
                            description: Bad request — invalid JSON payload or missing fields
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: integer
                                                example: 400
                                            error:
                                                type: string
                                                example: "Invalid payload."
                        '401':
                            description: Unauthorized — wrong credentials
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: integer
                                                example: 401
                                            error:
                                                type: string
                                                example: "Invalid credentials."
                        '500':
                            description: Internal server error
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: integer
                                                example: 500
                                            error:
                                                type: string
                                                example: "Internal server error"
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: demo@example.com
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
